server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cohort8ApiProject
    username: patika_user
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      '[hibernate.format_sql]': true
      #adsf

